In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('../data/flats.csv')
df.sample(5)

property_name  \
1104   2 BHK Flat in Sector 82 Gurgaon   
228   2 BHK Flat in Sector 37D Gurgaon   
577   2 BHK Flat in Sector 107 Gurgaon   
1421  2 BHK Flat in Sector 37C Gurgaon   
1915   2 BHK Flat in Sector 91 Gurgaon   

                                                   link  \
1104  https://www.99acres.com/2-bhk-bedroom-apartmen...   
228   https://www.99acres.com/2-bhk-bedroom-apartmen...   
577   https://www.99acres.com/2-bhk-bedroom-apartmen...   
1421  https://www.99acres.com/2-bhk-bedroom-apartmen...   
1915  https://www.99acres.com/2-bhk-bedroom-apartmen...   

                              society      price            area  \
1104      Vatika The Seven Lamps3.8 ★  94.25 Lac  ₹ 6,567/sq.ft.   
228   Ramprastha The Edge Towers3.5 ★     71 Lac  ₹ 5,420/sq.ft.   
577      Signature Global Solera3.7 ★  27.75 Lac  ₹ 5,674/sq.ft.   
1421                   Apex Our Homes     35 Lac  ₹ 3,783/sq.ft.   
1915                  TARC Maceo3.8 ★     90 Lac  ₹ 6,870/sq.ft.   

                                           areaWithType     bedRoom  \
1104             Super Built up area 1435(133.32 sq.m.)  2 Bedrooms   
228   Super Built up area 1310(121.7 sq.m.)Built Up ...  2 Bedrooms   
577                      Carpet area: 489 (45.43 sq.m.)  2 Bedrooms   
1421  Super Built up area 925(85.94 sq.m.)Built Up a...  2 Bedrooms   
1915              Super Built up area 1310(121.7 sq.m.)  2 Bedrooms   

         bathroom      balcony additionalRoom  \
1104  2 Bathrooms  2 Balconies     Study Room   
228   2 Bathrooms  3 Balconies         Others   
577   2 Bathrooms  2 Balconies            NaN   
1421  2 Bathrooms    1 Balcony            NaN   
1915  2 Bathrooms  2 Balconies            NaN   

                                            address             floorNum  \
1104            Sector 82 Gurgaon, Gurgaon, Haryana  12nd   of 16 Floors   
228   Gurgaon, Sector 37D Gurgaon, Gurgaon, Haryana  10th   of 22 Floors   
577            Sector 107 Gurgaon, Gurgaon, Haryana   6th   of 14 Floors   
1421      753, Sector 37C Gurgaon, Gurgaon, Haryana   7th   of 11 Floors   
1915            Sector 91 Gurgaon, Gurgaon, Haryana  13rd   of 13 Floors   

          facing    agePossession  \
1104        East  1 to 5 Year Old   
228   South-East  0 to 1 Year Old   
577         West  1 to 5 Year Old   
1421        East  1 to 5 Year Old   
1915        East  1 to 5 Year Old   

                                        nearbyLocations  \
1104  ['SS Omnia Mall', 'Golf Course Ext Rd', 'Knowl...   
228   ['MDS Public School', 'St Pauls School', 'Sunc...   
577   ['Gurgaon Dreamz Mall', 'Dwarka Expressway', "...   
1421  ['Elvedor Mall', 'MDS Public School', 'K.D. Ho...   
1915  ['Manish Gallexie 91', 'Dwarka Expressway', 'R...   

                                            description  \
1104  Brokers excuse, 2bhk, study, 1435 sq. Ft., nor...   
228   Residential apartment for sell.Located in sect...   
577   This lovely 2 bhk apartment/flat in sector 107...   
1421  Check out this 2 bhk apartment for sale in ape...   
1915                  Fully furnished east facing flat.   

                                         furnishDetails  \
1104  ['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '2 Ge...   
228                                                  []   
577                                                 NaN   
1421  ['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...   
1915  ['1 Water Purifier', '3 Fan', '1 Fridge', '1 D...   

                                               features  \
1104  ['Security / Fire Alarm', 'Feng Shui / Vaastu ...   
228   ['Intercom Facility', 'Lift(s)', 'Swimming Poo...   
577   ['Power Back-up', 'Intercom Facility', 'Lift(s...   
1421  ['Centrally Air Conditioned', 'Water purifier'...   
1915  ['Power Back-up', 'Intercom Facility', 'Lift(s...   

                                                 rating property_id  \
1104  ['Green Area5 out of 5', 'Construction5 out of...   J69790804   
228   ['Green Area4 out of 5', 'Amenities4 o

In [4]:
print(df.columns)

Index(['property_name', 'link', 'society', 'price', 'area', 'areaWithType',
       'bedRoom', 'bathroom', 'balcony', 'additionalRoom', 'address',
       'floorNum', 'facing', 'agePossession', 'nearbyLocations', 'description',
       'furnishDetails', 'features', 'rating', 'property_id', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28'],
      dtype='object')


In [5]:
df = df.drop(columns=['Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28'])
print(df.columns)

Index(['property_name', 'link', 'society', 'price', 'area', 'areaWithType',
       'bedRoom', 'bathroom', 'balcony', 'additionalRoom', 'address',
       'floorNum', 'facing', 'agePossession', 'nearbyLocations', 'description',
       'furnishDetails', 'features', 'rating', 'property_id'],
      dtype='object')


In [6]:
# shape
df.shape

(3017, 20)

In [7]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3017 entries, 0 to 3016
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   property_name    3017 non-null   object
 1   link             3017 non-null   object
 2   society          3016 non-null   object
 3   price            3007 non-null   object
 4   area             3004 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   

In [8]:
# check for duplicates
df.duplicated().sum()

np.int64(0)

In [9]:
# check for missing values
df.isnull().sum()

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

In [10]:
# Columns to drop -> property_name, link, property_id
df.drop(columns=['link','property_id'], inplace=True)

In [11]:
df.head()

property_name                 society       price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency      45 Lac   
1        2 BHK Flat in Ashok Vihar            Apna Enclave      50 Lac   
2              2 BHK Flat in Sohna  Tulsiani Easy in Homes      40 Lac   
3  2 BHK Flat in Sector 61 Gurgaon     Smart World Orchard  1.47 Crore   
4  2 BHK Flat in Sector 92 Gurgaon        Parkwood Westend      70 Lac   

              area                            areaWithType     bedRoom  \
0   ₹ 5,000/sq.ft.          Carpet area: 900 (83.61 sq.m.)  2 Bedrooms   
1   ₹ 7,692/sq.ft.          Carpet area: 650 (60.39 sq.m.)  2 Bedrooms   
2   ₹ 6,722/sq.ft.          Carpet area: 595 (55.28 sq.m.)  2 Bedrooms   
3  ₹ 12,250/sq.ft.        Carpet area: 1200 (111.48 sq.m.)  2 Bedrooms   
4   ₹ 5,204/sq.ft.  Super Built up area 1345(124.95 sq.m.)  2 Bedrooms   

      bathroom      balcony additionalRoom  \
0  2 Bathrooms    1 Balcony            NaN   
1  2 Bathrooms    1 Balcony            NaN   
2  2 Bathrooms  3 Balconies            NaN   
3  2 Bathrooms  2 Balconies     Study Room   
4  2 Bathrooms  3 Balconies     Study Room   

                               address             floorNum facing  \
0     Krishna Colony, Gurgaon, Haryana    4th   of 4 Floors   West   
1   46b, Ashok Vihar, Gurgaon, Haryana    1st   of 3 Floors   West   
2              Sohna, Gurgaon, Haryana  12nd   of 14 Floors    NaN   
3  Sector 61 Gurgaon, Gurgaon, Haryana    2nd   of 4 Floors    NaN   
4  Sector 92 Gurgaon, Gurgaon, Haryana    5th   of 8 Floors    NaN   

        agePossession                                    nearbyLocations  \
0     1 to 5 Year Old  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1        10+ Year Old  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2     0 to 1 Year Old  ['Huda City Metro', 'Golf Course extn road', '...   
3            Dec 2023  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  Under Construction  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [12]:
# rename columns
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

property_name                 society       price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency      45 Lac   
1        2 BHK Flat in Ashok Vihar            Apna Enclave      50 Lac   
2              2 BHK Flat in Sohna  Tulsiani Easy in Homes      40 Lac   
3  2 BHK Flat in Sector 61 Gurgaon     Smart World Orchard  1.47 Crore   
4  2 BHK Flat in Sector 92 Gurgaon        Parkwood Westend      70 Lac   

    price_per_sqft                            areaWithType     bedRoom  \
0   ₹ 5,000/sq.ft.          Carpet area: 900 (83.61 sq.m.)  2 Bedrooms   
1   ₹ 7,692/sq.ft.          Carpet area: 650 (60.39 sq.m.)  2 Bedrooms   
2   ₹ 6,722/sq.ft.          Carpet area: 595 (55.28 sq.m.)  2 Bedrooms   
3  ₹ 12,250/sq.ft.        Carpet area: 1200 (111.48 sq.m.)  2 Bedrooms   
4   ₹ 5,204/sq.ft.  Super Built up area 1345(124.95 sq.m.)  2 Bedrooms   

      bathroom      balcony additionalRoom  \
0  2 Bathrooms    1 Balcony            NaN   
1  2 Bathrooms    1 Balcony            NaN   
2  2 Bathrooms  3 Balconies            NaN   
3  2 Bathrooms  2 Balconies     Study Room   
4  2 Bathrooms  3 Balconies     Study Room   

                               address             floorNum facing  \
0     Krishna Colony, Gurgaon, Haryana    4th   of 4 Floors   West   
1   46b, Ashok Vihar, Gurgaon, Haryana    1st   of 3 Floors   West   
2              Sohna, Gurgaon, Haryana  12nd   of 14 Floors    NaN   
3  Sector 61 Gurgaon, Gurgaon, Haryana    2nd   of 4 Floors    NaN   
4  Sector 92 Gurgaon, Gurgaon, Haryana    5th   of 8 Floors    NaN   

        agePossession                                    nearbyLocations  \
0     1 to 5 Year Old  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1        10+ Year Old  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2     0 to 1 Year Old  ['Huda City Metro', 'Golf Course extn road', '...   
3            Dec 2023  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  Under Construction  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [13]:
# society
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Smart World Gems                                     32
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Orchard                                  32
DLF The Ultima4.0 ★                                  31
Paras Dews                                           31
DLF Regal Gardens3.9 ★                               30
Shree Vardhman Flora3.8 ★                            29
M3M Woodshire4.0 ★                                   29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★               

Comment: Need to clean text of society column. need to remove ratings

In [14]:
df['society'].value_counts().shape

(638,)

Comment: Total 638 unique values for society. But it may contain duplicates since smallcase e nei, rating o ache

In [15]:
# Removing unnecessary text from society column
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [16]:
df.head()

property_name                 society       price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency      45 Lac   
1        2 BHK Flat in Ashok Vihar            apna enclave      50 Lac   
2              2 BHK Flat in Sohna  tulsiani easy in homes      40 Lac   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard  1.47 Crore   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend      70 Lac   

    price_per_sqft                            areaWithType     bedRoom  \
0   ₹ 5,000/sq.ft.          Carpet area: 900 (83.61 sq.m.)  2 Bedrooms   
1   ₹ 7,692/sq.ft.          Carpet area: 650 (60.39 sq.m.)  2 Bedrooms   
2   ₹ 6,722/sq.ft.          Carpet area: 595 (55.28 sq.m.)  2 Bedrooms   
3  ₹ 12,250/sq.ft.        Carpet area: 1200 (111.48 sq.m.)  2 Bedrooms   
4   ₹ 5,204/sq.ft.  Super Built up area 1345(124.95 sq.m.)  2 Bedrooms   

      bathroom      balcony additionalRoom  \
0  2 Bathrooms    1 Balcony            NaN   
1  2 Bathrooms    1 Balcony            NaN   
2  2 Bathrooms  3 Balconies            NaN   
3  2 Bathrooms  2 Balconies     Study Room   
4  2 Bathrooms  3 Balconies     Study Room   

                               address             floorNum facing  \
0     Krishna Colony, Gurgaon, Haryana    4th   of 4 Floors   West   
1   46b, Ashok Vihar, Gurgaon, Haryana    1st   of 3 Floors   West   
2              Sohna, Gurgaon, Haryana  12nd   of 14 Floors    NaN   
3  Sector 61 Gurgaon, Gurgaon, Haryana    2nd   of 4 Floors    NaN   
4  Sector 92 Gurgaon, Gurgaon, Haryana    5th   of 8 Floors    NaN   

        agePossession                                    nearbyLocations  \
0     1 to 5 Year Old  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1        10+ Year Old  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2     0 to 1 Year Old  ['Huda City Metro', 'Golf Course extn road', '...   
3            Dec 2023  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  Under Construction  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [17]:
df['society'].value_counts().shape

(604,)

Comment: Now total 604 unique values for society.

In [18]:
df['society'].value_counts()

society
tulip violet                                     75
ss the leaf                                      74
shapoorji pallonji joyville gurugram             45
dlf new town heights                             38
signature global park                            36
shree vardhman victoria                          35
emaar mgf emerald floors premier                 32
smart world gems                                 32
smart world orchard                              32
paras dews                                       31
dlf the ultima                                   31
dlf regal gardens                                30
m3m woodshire                                    30
shree vardhman flora                             29
signature global solera                          28
la vida by tata housing                          28
godrej nature plus                               27
bptp terra                                       25
emaar gurgaon greens                             25
vati

In [19]:
df.head()

property_name                 society       price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency      45 Lac   
1        2 BHK Flat in Ashok Vihar            apna enclave      50 Lac   
2              2 BHK Flat in Sohna  tulsiani easy in homes      40 Lac   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard  1.47 Crore   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend      70 Lac   

    price_per_sqft                            areaWithType     bedRoom  \
0   ₹ 5,000/sq.ft.          Carpet area: 900 (83.61 sq.m.)  2 Bedrooms   
1   ₹ 7,692/sq.ft.          Carpet area: 650 (60.39 sq.m.)  2 Bedrooms   
2   ₹ 6,722/sq.ft.          Carpet area: 595 (55.28 sq.m.)  2 Bedrooms   
3  ₹ 12,250/sq.ft.        Carpet area: 1200 (111.48 sq.m.)  2 Bedrooms   
4   ₹ 5,204/sq.ft.  Super Built up area 1345(124.95 sq.m.)  2 Bedrooms   

      bathroom      balcony additionalRoom  \
0  2 Bathrooms    1 Balcony            NaN   
1  2 Bathrooms    1 Balcony            NaN   
2  2 Bathrooms  3 Balconies            NaN   
3  2 Bathrooms  2 Balconies     Study Room   
4  2 Bathrooms  3 Balconies     Study Room   

                               address             floorNum facing  \
0     Krishna Colony, Gurgaon, Haryana    4th   of 4 Floors   West   
1   46b, Ashok Vihar, Gurgaon, Haryana    1st   of 3 Floors   West   
2              Sohna, Gurgaon, Haryana  12nd   of 14 Floors    NaN   
3  Sector 61 Gurgaon, Gurgaon, Haryana    2nd   of 4 Floors    NaN   
4  Sector 92 Gurgaon, Gurgaon, Haryana    5th   of 8 Floors    NaN   

        agePossession                                    nearbyLocations  \
0     1 to 5 Year Old  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1        10+ Year Old  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2     0 to 1 Year Old  ['Huda City Metro', 'Golf Course extn road', '...   
3            Dec 2023  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  Under Construction  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [20]:
# price
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.2 Crore           59
1.5 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.9 Crore           40
1.55 Crore          40
75 Lac              38
1.65 Crore          38
1.7 Crore           37
1.8 Crore           37
80 Lac              36
2.2 Crore           34
1.15 Crore          33
50 Lac              33
85 Lac              31
1.45 Crore          31
1.05 Crore          30
60 Lac              29
40 Lac              29
2.5 Crore           29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
1.85 Crore          23
2.35 Crore          23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.3 Crore           18
2.4 Crore           18
30 Lac              17
2.65 

Comment: Need to remove rows where price = "Price on Request"

In [21]:
df[df['price'] == 'Price on Request']

property_name                    society  \
25      5 BHK Flat in Sector 1 Gurgaon  the new people apartments   
1644   4 BHK Flat in Sector 50 Gurgaon                ss hibiscus   
1972   1 BHK Flat in Sector 31 Gurgaon            raheja atlantis   
2054   2 BHK Flat in Sector 79 Gurgaon         supertech araville   
2357  2 BHK Flat in Sector 37D Gurgaon            the millennia 2   
2522  2 BHK Flat in Sector 95A Gurgaon              the roselia 2   
2549      3 BHK Flat in Sector-2 Sohna         supertech hilltown   
2640  2 BHK Flat in Sector 95A Gurgaon              the roselia 2   
2959  3 BHK Flat in Sector 104 Gurgaon              godrej summit   
2972         4 BHK Flat in Gwal Pahari     krrish provence estate   
2973   4 BHK Flat in Sector 95 Gurgaon    sidhartha ncr one phase   

                 price price_per_sqft  \
25    Price on Request            NaN   
1644  Price on Request            NaN   
1972  Price on Request            NaN   
2054  Price on Request            NaN   
2357  Price on Request            NaN   
2522  Price on Request            NaN   
2549  Price on Request            NaN   
2640  Price on Request            NaN   
2959  Price on Request            NaN   
2972  Price on Request            NaN   
2973  Price on Request            NaN   

                                           areaWithType     bedRoom  \
25                   Built Up area: 4500 (418.06 sq.m.)  5 Bedrooms   
1644                   Carpet area: 4800 (445.93 sq.m.)  4 Bedrooms   
1972                     Carpet area: 650 (60.39 sq.m.)   1 Bedroom   
2054                 Built Up area: 1295 (120.31 sq.m.)  2 Bedrooms   
2357                     Carpet area: 552 (51.28 sq.m.)  2 Bedrooms   
2522                     Carpet area: 593 (55.09 sq.m.)  2 Bedrooms   
2549                 Built Up area: 1720 (159.79 sq.m.)  3 Bedrooms   
2640                     Carpet area: 593 (55.09 sq.m.)  2 Bedrooms   
2959  Super Built up area 1647(153.01 sq.m.)Carpet a...  3 Bedrooms   
2972                 Built Up area: 5800 (538.84 sq.m.)  4 Bedrooms   
2973             Super Built up area 2354(218.69 sq.m.)  4 Bedrooms   

         bathroom       balcony                      additionalRoom  \
25     1 Bathroom    No Balcony                                 NaN   
1644  4 Bathrooms   3 Balconies                        Servant Room   
1972   1 Bathroom     1 Balcony  Pooja Room,Study Room,Servant Room   
2054  2 Bathrooms    No Balcony                                 NaN   
2357   1 Bathroom     1 Balcony                                 NaN   
2522  2 Bathrooms   2 Balconies                                 NaN   
2549  3 Bathrooms   3 Balconies                                 NaN   
2640  2 Bathrooms   2 Balconies                                 NaN   
2959  3 Bathrooms   3 Balconies                                 NaN   
2972  5 Bathrooms     1 Balcony                                 NaN   
2973  4 Bathrooms  3+ Balconies                                 NaN   

                                                address             floorNum  \
25         Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana   Ground of 1 Floors   
1644                Sector 50 Gurgaon, Gurgaon, Haryana   7th   of 18 Floors   
1972           Yes, Sector 31 Gurgaon, Gurgaon, Haryana   3rd   of 15 Floors   
2054     Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana  15th   of 15 Floors   
2357               Sector 37D Gurgaon, Gurgaon, Haryana  13rd   of 13 Floors   
2522  Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...  14th   of 14 Floors   
2549  Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...    4th   of 4 Floors   
2640  Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...  14th   of 14 Floors   
2959         1402, Sector 104 Gurgaon, Gurgaon, Haryana  14th   of 17 Floors   
2972                      Gwal Pahari, Gurgaon, Haryana  17th   of 24 Floors   
2973                Sector 95 Gurgaon, Gurgaon, Haryana   Ground of 3 Floors   

          facing       agePossession

In [22]:
# Removing rows where price = "Price on Request"
df = df[df['price'] != 'Price on Request']

In [23]:
df.head()

property_name                 society       price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency      45 Lac   
1        2 BHK Flat in Ashok Vihar            apna enclave      50 Lac   
2              2 BHK Flat in Sohna  tulsiani easy in homes      40 Lac   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard  1.47 Crore   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend      70 Lac   

    price_per_sqft                            areaWithType     bedRoom  \
0   ₹ 5,000/sq.ft.          Carpet area: 900 (83.61 sq.m.)  2 Bedrooms   
1   ₹ 7,692/sq.ft.          Carpet area: 650 (60.39 sq.m.)  2 Bedrooms   
2   ₹ 6,722/sq.ft.          Carpet area: 595 (55.28 sq.m.)  2 Bedrooms   
3  ₹ 12,250/sq.ft.        Carpet area: 1200 (111.48 sq.m.)  2 Bedrooms   
4   ₹ 5,204/sq.ft.  Super Built up area 1345(124.95 sq.m.)  2 Bedrooms   

      bathroom      balcony additionalRoom  \
0  2 Bathrooms    1 Balcony            NaN   
1  2 Bathrooms    1 Balcony            NaN   
2  2 Bathrooms  3 Balconies            NaN   
3  2 Bathrooms  2 Balconies     Study Room   
4  2 Bathrooms  3 Balconies     Study Room   

                               address             floorNum facing  \
0     Krishna Colony, Gurgaon, Haryana    4th   of 4 Floors   West   
1   46b, Ashok Vihar, Gurgaon, Haryana    1st   of 3 Floors   West   
2              Sohna, Gurgaon, Haryana  12nd   of 14 Floors    NaN   
3  Sector 61 Gurgaon, Gurgaon, Haryana    2nd   of 4 Floors    NaN   
4  Sector 92 Gurgaon, Gurgaon, Haryana    5th   of 8 Floors    NaN   

        agePossession                                    nearbyLocations  \
0     1 to 5 Year Old  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1        10+ Year Old  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2     0 to 1 Year Old  ['Huda City Metro', 'Golf Course extn road', '...   
3            Dec 2023  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  Under Construction  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [24]:
df['price'].value_counts()

price
1.25 Crore     79
1.1 Crore      61
1.4 Crore      60
1.2 Crore      59
1.5 Crore      59
90 Lac         58
1.3 Crore      57
95 Lac         53
2 Crore        51
1.75 Crore     47
1 Crore        46
1.6 Crore      43
1.35 Crore     41
1.9 Crore      40
1.55 Crore     40
75 Lac         38
1.65 Crore     38
1.8 Crore      37
1.7 Crore      37
80 Lac         36
2.2 Crore      34
1.15 Crore     33
50 Lac         33
1.45 Crore     31
85 Lac         31
1.05 Crore     30
2.5 Crore      29
60 Lac         29
40 Lac         29
2.1 Crore      26
45 Lac         26
65 Lac         25
35 Lac         23
1.85 Crore     23
2.35 Crore     23
3 Crore        22
70 Lac         21
2.25 Crore     20
55 Lac         20
3.5 Crore      19
2.3 Crore      18
2.4 Crore      18
30 Lac         17
2.65 Crore     16
1.38 Crore     15
2.6 Crore      15
2.45 Crore     14
3.4 Crore      14
2.15 Crore     14
82 Lac         13
78 Lac         13
38 Lac         13
92 Lac         13
2.7 Crore      13
1.32 Crore     13
3.25

Comments: Price are in different units. 'Lac' and 'Crore'. So, bringing all of the datapoints into same unit 'Crore'

In [25]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [26]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [27]:
df['price'].value_counts()

price
1.25     79
1.10     61
0.90     60
1.40     60
1.50     59
1.20     59
1.30     57
0.95     55
2.00     51
1.75     47
1.00     46
1.60     43
1.35     41
1.55     40
1.90     40
0.75     38
1.65     38
1.80     37
1.70     37
0.80     37
2.20     34
1.15     33
0.50     33
0.85     32
0.40     31
1.45     31
1.05     30
2.50     29
0.60     29
0.65     28
2.10     26
0.45     26
0.35     24
1.85     23
2.35     23
0.55     22
3.00     22
0.70     21
2.25     20
0.30     19
3.50     19
2.30     18
2.40     18
0.28     17
2.65     16
1.38     15
0.78     15
0.88     15
2.60     15
0.82     14
2.15     14
0.38     14
2.45     14
3.40     14
0.32     14
2.70     13
0.36     13
1.32     13
3.25     13
0.92     13
0.26     13
0.42     13
1.42     12
0.56     12
1.95     12
2.80     12
0.27     12
0.87     12
5.00     12
0.98     11
0.25     11
1.08     11
0.99     11
0.71     10
0.72     10
1.78     10
1.12     10
1.28     10
2.55     10
2.05      9
4.00      9
3.45      9
1.72      

In [28]:
df.head(5)

property_name                 society  price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency   0.45   
1        2 BHK Flat in Ashok Vihar            apna enclave   0.50   
2              2 BHK Flat in Sohna  tulsiani easy in homes   0.40   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard   1.47   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend   0.70   

    price_per_sqft                            areaWithType     bedRoom  \
0   ₹ 5,000/sq.ft.          Carpet area: 900 (83.61 sq.m.)  2 Bedrooms   
1   ₹ 7,692/sq.ft.          Carpet area: 650 (60.39 sq.m.)  2 Bedrooms   
2   ₹ 6,722/sq.ft.          Carpet area: 595 (55.28 sq.m.)  2 Bedrooms   
3  ₹ 12,250/sq.ft.        Carpet area: 1200 (111.48 sq.m.)  2 Bedrooms   
4   ₹ 5,204/sq.ft.  Super Built up area 1345(124.95 sq.m.)  2 Bedrooms   

      bathroom      balcony additionalRoom  \
0  2 Bathrooms    1 Balcony            NaN   
1  2 Bathrooms    1 Balcony            NaN   
2  2 Bathrooms  3 Balconies            NaN   
3  2 Bathrooms  2 Balconies     Study Room   
4  2 Bathrooms  3 Balconies     Study Room   

                               address             floorNum facing  \
0     Krishna Colony, Gurgaon, Haryana    4th   of 4 Floors   West   
1   46b, Ashok Vihar, Gurgaon, Haryana    1st   of 3 Floors   West   
2              Sohna, Gurgaon, Haryana  12nd   of 14 Floors    NaN   
3  Sector 61 Gurgaon, Gurgaon, Haryana    2nd   of 4 Floors    NaN   
4  Sector 92 Gurgaon, Gurgaon, Haryana    5th   of 8 Floors    NaN   

        agePossession                                    nearbyLocations  \
0     1 to 5 Year Old  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1        10+ Year Old  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2     0 to 1 Year Old  ['Huda City Metro', 'Golf Course extn road', '...   
3            Dec 2023  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  Under Construction  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [29]:
# price_per_sqft
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 12,500/sq.ft.     16
₹ 8,000/sq.ft.      16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 8,333/sq.ft.      12
₹ 7,500/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 12,000/sq.ft.      8
₹ 7,000/sq.ft.       8
₹ 9,000/sq.ft.       7
₹ 11,111/sq.ft.      6
₹ 6,578/sq.ft.       6
₹ 9,230/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 5,500/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 5,600/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 10,714/sq.ft.      5
₹ 4,444/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 7,641/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 7,142/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 7,407/sq.ft.       5
₹ 4,666/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 6,500/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 7,692/sq.ft.       5
₹ 10,416/sq.ft.      4
₹ 8,432/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 7,250/sq.ft.     

Comment: we only need the number in price_per_sqft, need to remove extra contents

In [30]:
df[df['price_per_sqft'].isnull()]

property_name                            society  \
18     2 BHK Flat in Sector 93 Gurgaon  signature global orchard avenue 2   
2849  2 BHK Flat in Sector 107 Gurgaon            signature global solera   

      price price_per_sqft                       areaWithType     bedRoom  \
18      NaN            NaN  Carpet area: 577.11 (53.62 sq.m.)  2 Bedrooms   
2849    NaN            NaN                                NaN         NaN   

         bathroom      balcony additionalRoom  \
18    2 Bathrooms  3 Balconies            NaN   
2849          NaN          NaN            NaN   

                                          address             floorNum facing  \
18    L-1104, Sector 93 Gurgaon, Gurgaon, Haryana  11st   of 14 Floors   East   
2849                                          NaN                  NaN    NaN   

           agePossession                                    nearbyLocations  \
18    Under Construction  ['Huda Metro Station', 'V3S Sapphire Ninety', ...   
2849                 NaN                                                NaN   

                                            description furnishDetails  \
18    Looking for a budget-Friendly 2 bhk flat in a ...            NaN   
2849                                                NaN            NaN   

                                               features rating  
18    ['Security / Fire Alarm', 'Feng Shui / Vaastu ...    NaN  
2849                                                NaN    NaN

In [31]:
# astype float bcoz it contains nan values
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [32]:
df['price_per_sqft'].value_counts()

price_per_sqft
10000.0     19
12500.0     16
8000.0      16
6666.0      13
5000.0      13
8333.0      12
7500.0      12
6000.0      11
8461.0       9
12000.0      8
7000.0       8
9000.0       7
11111.0      6
6578.0       6
9230.0       6
8888.0       6
8928.0       6
5500.0       6
11500.0      6
5600.0       5
11428.0      5
10714.0      5
4444.0       5
14242.0      5
7641.0       5
8571.0       5
8205.0       5
7142.0       5
16000.0      5
7407.0       5
4666.0       5
4615.0       5
6500.0       5
5556.0       5
5384.0       5
7692.0       5
10416.0      4
8432.0       4
4687.0       4
4814.0       4
8163.0       4
11666.0      4
7250.0       4
16666.0      4
13913.0      4
8358.0       4
7272.0       4
9090.0       4
9210.0       4
4500.0       4
8484.0       4
8139.0       4
4854.0       4
10383.0      4
5660.0       4
8500.0       4
8784.0       4
8445.0       4
7317.0       4
15384.0      4
8474.0       4
8043.0       4
8108.0       4
14418.0      4
6250.0       4
9822.0    

In [33]:
df.head()

property_name                 society  price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency   0.45   
1        2 BHK Flat in Ashok Vihar            apna enclave   0.50   
2              2 BHK Flat in Sohna  tulsiani easy in homes   0.40   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard   1.47   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend   0.70   

   price_per_sqft                            areaWithType     bedRoom  \
0          5000.0          Carpet area: 900 (83.61 sq.m.)  2 Bedrooms   
1          7692.0          Carpet area: 650 (60.39 sq.m.)  2 Bedrooms   
2          6722.0          Carpet area: 595 (55.28 sq.m.)  2 Bedrooms   
3         12250.0        Carpet area: 1200 (111.48 sq.m.)  2 Bedrooms   
4          5204.0  Super Built up area 1345(124.95 sq.m.)  2 Bedrooms   

      bathroom      balcony additionalRoom  \
0  2 Bathrooms    1 Balcony            NaN   
1  2 Bathrooms    1 Balcony            NaN   
2  2 Bathrooms  3 Balconies            NaN   
3  2 Bathrooms  2 Balconies     Study Room   
4  2 Bathrooms  3 Balconies     Study Room   

                               address             floorNum facing  \
0     Krishna Colony, Gurgaon, Haryana    4th   of 4 Floors   West   
1   46b, Ashok Vihar, Gurgaon, Haryana    1st   of 3 Floors   West   
2              Sohna, Gurgaon, Haryana  12nd   of 14 Floors    NaN   
3  Sector 61 Gurgaon, Gurgaon, Haryana    2nd   of 4 Floors    NaN   
4  Sector 92 Gurgaon, Gurgaon, Haryana    5th   of 8 Floors    NaN   

        agePossession                                    nearbyLocations  \
0     1 to 5 Year Old  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1        10+ Year Old  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2     0 to 1 Year Old  ['Huda City Metro', 'Golf Course extn road', '...   
3            Dec 2023  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  Under Construction  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [34]:
# bedrooms
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [35]:
df[df['bedRoom'].isnull()]

property_name                       society  \
2849           2 BHK Flat in Sector 107 Gurgaon       signature global solera   
2850            4 BHK Flat in Sector 53 Gurgaon                tulip monsella   
2851              2 BHK Flat in New Palam Vihar                       my home   
2852                        2 BHK Flat in Sohna        breez global hill view   
2922           3 BHK Flat in Sector 99A Gurgaon      pareena coban residences   
2923         1 BHK Flat in Golf Course Ext Road  ikon tower baani city centre   
2924            2 BHK Flat in Sector 89 Gurgaon                   greenopolis   
2926  4 BHK Flat in C Block Sushant Lok Phase 1                 maple heights   
2927            2 BHK Flat in Sector 99 Gurgaon                assotech blith   

      price  price_per_sqft areaWithType bedRoom bathroom balcony  \
2849    NaN             NaN          NaN     NaN      NaN     NaN   
2850    NaN         33198.0          NaN     NaN      NaN     NaN   
2851    NaN          4400.0          NaN     NaN      NaN     NaN   
2852    NaN          5470.0          NaN     NaN      NaN     NaN   
2922    NaN          5759.0          NaN     NaN      NaN     NaN   
2923    NaN         12437.0          NaN     NaN      NaN     NaN   
2924    NaN          4820.0          NaN     NaN      NaN     NaN   
2926    NaN          8888.0          NaN     NaN      NaN     NaN   
2927    NaN          6593.0          NaN     NaN      NaN     NaN   

     additionalRoom address floorNum facing agePossession nearbyLocations  \
2849            NaN     NaN      NaN    NaN           NaN             NaN   
2850            NaN     NaN      NaN    NaN           NaN             NaN   
2851            NaN     NaN      NaN    NaN           NaN             NaN   
2852            NaN     NaN      NaN    NaN           NaN             NaN   
2922            NaN     NaN      NaN    NaN           NaN             NaN   
2923            NaN     NaN      NaN    NaN           NaN             NaN   
2924            NaN     NaN      NaN    NaN           NaN             NaN   
2926            NaN     NaN      NaN    NaN           NaN             NaN   
2927            NaN     NaN      NaN    NaN           NaN             NaN   

     description furnishDetails features rating  
2849         NaN            NaN      NaN    NaN  
2850         NaN            NaN      NaN    NaN  
2851         NaN            NaN      NaN    NaN  
2852         NaN            NaN      NaN    NaN  
2922         NaN            NaN      NaN    NaN  
2923         NaN            NaN      NaN    NaN  
2924         NaN            NaN      NaN    NaN  
2926         NaN            NaN      NaN    NaN  
2927         NaN            NaN      NaN    NaN

Comment: Those rows which contains NaN in bedRoom also contains NaN in other columns. So removing those rows.

In [36]:
df = df[~df['bedRoom'].isnull()]

In [37]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [38]:
# only need the number and since no NaN values, so astype('int')
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [39]:
df.head()

property_name                 society  price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency   0.45   
1        2 BHK Flat in Ashok Vihar            apna enclave   0.50   
2              2 BHK Flat in Sohna  tulsiani easy in homes   0.40   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard   1.47   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend   0.70   

   price_per_sqft                            areaWithType  bedRoom  \
0          5000.0          Carpet area: 900 (83.61 sq.m.)        2   
1          7692.0          Carpet area: 650 (60.39 sq.m.)        2   
2          6722.0          Carpet area: 595 (55.28 sq.m.)        2   
3         12250.0        Carpet area: 1200 (111.48 sq.m.)        2   
4          5204.0  Super Built up area 1345(124.95 sq.m.)        2   

      bathroom      balcony additionalRoom  \
0  2 Bathrooms    1 Balcony            NaN   
1  2 Bathrooms    1 Balcony            NaN   
2  2 Bathrooms  3 Balconies            NaN   
3  2 Bathrooms  2 Balconies     Study Room   
4  2 Bathrooms  3 Balconies     Study Room   

                               address             floorNum facing  \
0     Krishna Colony, Gurgaon, Haryana    4th   of 4 Floors   West   
1   46b, Ashok Vihar, Gurgaon, Haryana    1st   of 3 Floors   West   
2              Sohna, Gurgaon, Haryana  12nd   of 14 Floors    NaN   
3  Sector 61 Gurgaon, Gurgaon, Haryana    2nd   of 4 Floors    NaN   
4  Sector 92 Gurgaon, Gurgaon, Haryana    5th   of 8 Floors    NaN   

        agePossession                                    nearbyLocations  \
0     1 to 5 Year Old  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1        10+ Year Old  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2     0 to 1 Year Old  ['Huda City Metro', 'Golf Course extn road', '...   
3            Dec 2023  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  Under Construction  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [40]:
# bathroom
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [41]:
df['bathroom'].isnull().sum()

np.int64(0)

In [42]:
# only need the number and since no NaN values, so astype('int')
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [43]:
df.head()

property_name                 society  price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency   0.45   
1        2 BHK Flat in Ashok Vihar            apna enclave   0.50   
2              2 BHK Flat in Sohna  tulsiani easy in homes   0.40   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard   1.47   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend   0.70   

   price_per_sqft                            areaWithType  bedRoom  bathroom  \
0          5000.0          Carpet area: 900 (83.61 sq.m.)        2         2   
1          7692.0          Carpet area: 650 (60.39 sq.m.)        2         2   
2          6722.0          Carpet area: 595 (55.28 sq.m.)        2         2   
3         12250.0        Carpet area: 1200 (111.48 sq.m.)        2         2   
4          5204.0  Super Built up area 1345(124.95 sq.m.)        2         2   

       balcony additionalRoom                              address  \
0    1 Balcony            NaN     Krishna Colony, Gurgaon, Haryana   
1    1 Balcony            NaN   46b, Ashok Vihar, Gurgaon, Haryana   
2  3 Balconies            NaN              Sohna, Gurgaon, Haryana   
3  2 Balconies     Study Room  Sector 61 Gurgaon, Gurgaon, Haryana   
4  3 Balconies     Study Room  Sector 92 Gurgaon, Gurgaon, Haryana   

              floorNum facing       agePossession  \
0    4th   of 4 Floors   West     1 to 5 Year Old   
1    1st   of 3 Floors   West        10+ Year Old   
2  12nd   of 14 Floors    NaN     0 to 1 Year Old   
3    2nd   of 4 Floors    NaN            Dec 2023   
4    5th   of 8 Floors    NaN  Under Construction   

                                     nearbyLocations  \
0  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2  ['Huda City Metro', 'Golf Course extn road', '...   
3  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [44]:
# balcony
df['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

Comment: 'balcony' need only number, so need to remove extra text. Also since 3+ is there, can't convert it to int or float, need to keep it in string format only.

In [45]:
df['balcony'].isnull().sum()

np.int64(0)

In [46]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [47]:
df['balcony'].value_counts()

balcony
3     974
3+    862
2     749
1     315
0      97
Name: count, dtype: int64

In [48]:
df.head()

property_name                 society  price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency   0.45   
1        2 BHK Flat in Ashok Vihar            apna enclave   0.50   
2              2 BHK Flat in Sohna  tulsiani easy in homes   0.40   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard   1.47   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend   0.70   

   price_per_sqft                            areaWithType  bedRoom  bathroom  \
0          5000.0          Carpet area: 900 (83.61 sq.m.)        2         2   
1          7692.0          Carpet area: 650 (60.39 sq.m.)        2         2   
2          6722.0          Carpet area: 595 (55.28 sq.m.)        2         2   
3         12250.0        Carpet area: 1200 (111.48 sq.m.)        2         2   
4          5204.0  Super Built up area 1345(124.95 sq.m.)        2         2   

  balcony additionalRoom                              address  \
0       1            NaN     Krishna Colony, Gurgaon, Haryana   
1       1            NaN   46b, Ashok Vihar, Gurgaon, Haryana   
2       3            NaN              Sohna, Gurgaon, Haryana   
3       2     Study Room  Sector 61 Gurgaon, Gurgaon, Haryana   
4       3     Study Room  Sector 92 Gurgaon, Gurgaon, Haryana   

              floorNum facing       agePossession  \
0    4th   of 4 Floors   West     1 to 5 Year Old   
1    1st   of 3 Floors   West        10+ Year Old   
2  12nd   of 14 Floors    NaN     0 to 1 Year Old   
3    2nd   of 4 Floors    NaN            Dec 2023   
4    5th   of 8 Floors    NaN  Under Construction   

                                     nearbyLocations  \
0  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2  ['Huda City Metro', 'Golf Course extn road', '...   
3  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [49]:
# additionalRoom
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Servant Room,Study Room                            8
Study Room,Pooja Room                              8
Study Room,Servant Room,Store Room                 7
Pooja Room,Servant Room,Others 

In [50]:
df['additionalRoom'].value_counts().shape

(49,)

In [51]:
df['additionalRoom'].isnull().sum()

np.int64(1305)

Comment: Many types of extra rooms like puja, servant... also too many NaN values

In [52]:
# replacing NaN values with 'not available' string
df['additionalRoom'].fillna('not available',inplace=True)

/tmp/ipykernel_5776/591493101.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available',inplace=True)


In [53]:
# converting content of additionalRoom column in lowercase
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [54]:
df['additionalRoom'].value_counts()

additionalRoom
not available                                    1305
servant room                                      629
study room                                        232
others                                            179
pooja room                                        132
study room,servant room                            81
store room                                         76
pooja room,servant room                            60
servant room,others                                52
servant room,pooja room                            30
study room,others                                  27
pooja room,study room,servant room,others          25
pooja room,study room,servant room                 24
servant room,store room                            19
pooja room,study room                              13
pooja room,study room,servant room,store room      12
servant room,study room                             8
study room,pooja room                               8
study room,se

In [55]:
df.head()

property_name                 society  price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency   0.45   
1        2 BHK Flat in Ashok Vihar            apna enclave   0.50   
2              2 BHK Flat in Sohna  tulsiani easy in homes   0.40   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard   1.47   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend   0.70   

   price_per_sqft                            areaWithType  bedRoom  bathroom  \
0          5000.0          Carpet area: 900 (83.61 sq.m.)        2         2   
1          7692.0          Carpet area: 650 (60.39 sq.m.)        2         2   
2          6722.0          Carpet area: 595 (55.28 sq.m.)        2         2   
3         12250.0        Carpet area: 1200 (111.48 sq.m.)        2         2   
4          5204.0  Super Built up area 1345(124.95 sq.m.)        2         2   

  balcony additionalRoom                              address  \
0       1  not available     Krishna Colony, Gurgaon, Haryana   
1       1  not available   46b, Ashok Vihar, Gurgaon, Haryana   
2       3  not available              Sohna, Gurgaon, Haryana   
3       2     study room  Sector 61 Gurgaon, Gurgaon, Haryana   
4       3     study room  Sector 92 Gurgaon, Gurgaon, Haryana   

              floorNum facing       agePossession  \
0    4th   of 4 Floors   West     1 to 5 Year Old   
1    1st   of 3 Floors   West        10+ Year Old   
2  12nd   of 14 Floors    NaN     0 to 1 Year Old   
3    2nd   of 4 Floors    NaN            Dec 2023   
4    5th   of 8 Floors    NaN  Under Construction   

                                     nearbyLocations  \
0  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2  ['Huda City Metro', 'Golf Course extn road', '...   
3  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [56]:
# floor num
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
2nd   of 2 Floors           26
1st   of 14 Floors          26
3rd   of 3 Floors           26
8th   of 19 Floors          24
5th   of 14 Floors          24
3rd   of 14 Floors          24
1st   of 1 Floors           23
9th   of 9 Floors           23
9th   of 14 Floors          23
11st   of 14 Floors         23
2nd   of 3 Floors           22
5th   of 12 Floors          22
2nd   of 14 Floors          21
8th   of 18 Floors          20
10th   of 19 Floors         18
6th   of 18 Floors          18
7th   of 15 Floors          17
Ground of 1 Floors          17
7th   of 18 Floors          17
10th   of 18 Floors         17

In [57]:
df['floorNum'].isnull().sum()

np.int64(2)

In [58]:
df[df['floorNum'].isnull()]

property_name             society  price  \
181   3 BHK Flat in Dwarka Expressway Gurgaon  experion heartsong   1.08   
2766          2 BHK Flat in Sector 78 Gurgaon                 nan   0.60   

      price_per_sqft                        areaWithType  bedRoom  bathroom  \
181           6150.0  Built Up area: 1758 (163.32 sq.m.)        3         3   
2766          3692.0  Built Up area: 1625 (150.97 sq.m.)        2         2   

     balcony additionalRoom  \
181        0  not available   
2766       0  not available   

                                                address floorNum facing  \
181   604, Tower B-3, 6th Floor,Sector 108, Dwarka E...      NaN    NaN   
2766       Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana      NaN    NaN   

           agePossession nearbyLocations  \
181   Under Construction             NaN   
2766  Under Construction             NaN   

                                            description furnishDetails  \
181   A property by one of the most reputed builders...             []   
2766  The property is under construction it's by rah...             []   

     features                                             rating  
181       NaN                                                NaN  
2766      NaN  ['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...

In [59]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [60]:
df['floorNum'].value_counts()

floorNum
2     258
3     248
1     223
4     203
8     200
7     188
10    185
6     185
5     172
9     171
12    160
0     133
14    117
11    115
15     83
16     53
17     51
13     43
18     38
19     34
20     25
21     15
23     15
22     14
24     11
25      9
27      7
26      5
30      5
31      4
28      4
33      3
29      3
32      2
43      2
35      2
39      2
40      2
34      2
38      1
44      1
45      1
Name: count, dtype: int64

In [61]:
df[df['floorNum'].isnull()]

property_name             society  price  \
181   3 BHK Flat in Dwarka Expressway Gurgaon  experion heartsong   1.08   
2766          2 BHK Flat in Sector 78 Gurgaon                 nan   0.60   

      price_per_sqft                        areaWithType  bedRoom  bathroom  \
181           6150.0  Built Up area: 1758 (163.32 sq.m.)        3         3   
2766          3692.0  Built Up area: 1625 (150.97 sq.m.)        2         2   

     balcony additionalRoom  \
181        0  not available   
2766       0  not available   

                                                address floorNum facing  \
181   604, Tower B-3, 6th Floor,Sector 108, Dwarka E...      NaN    NaN   
2766       Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana      NaN    NaN   

           agePossession nearbyLocations  \
181   Under Construction             NaN   
2766  Under Construction             NaN   

                                            description furnishDetails  \
181   A property by one of the most reputed builders...             []   
2766  The property is under construction it's by rah...             []   

     features                                             rating  
181       NaN                                                NaN  
2766      NaN  ['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 0 to 3016
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   property_name    2997 non-null   object 
 1   society          2997 non-null   object 
 2   price            2996 non-null   float64
 3   price_per_sqft   2996 non-null   float64
 4   areaWithType     2997 non-null   object 
 5   bedRoom          2997 non-null   int64  
 6   bathroom         2997 non-null   int64  
 7   balcony          2997 non-null   object 
 8   additionalRoom   2997 non-null   object 
 9   address          2991 non-null   object 
 10  floorNum         2995 non-null   object 
 11  facing           2123 non-null   object 
 12  agePossession    2996 non-null   object 
 13  nearbyLocations  2906 non-null   object 
 14  description      2997 non-null   object 
 15  furnishDetails   2200 non-null   object 
 16  features         2590 non-null   object 
 17  rating           26

In [63]:
# updating 181th index floorNum from description
df.at[181,'floorNum'] = '6'

In [64]:
df[df['floorNum'].isnull()]

property_name society  price  price_per_sqft  \
2766  2 BHK Flat in Sector 78 Gurgaon     nan    0.6          3692.0   

                            areaWithType  bedRoom  bathroom balcony  \
2766  Built Up area: 1625 (150.97 sq.m.)        2         2       0   

     additionalRoom                                       address floorNum  \
2766  not available  Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana      NaN   

     facing       agePossession nearbyLocations  \
2766    NaN  Under Construction             NaN   

                                            description furnishDetails  \
2766  The property is under construction it's by rah...             []   

     features                                             rating  
2766      NaN  ['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...

In [65]:
# Dropping row 2766 since NaN value in floorNum
df = df.drop(2766)
df[df['floorNum'].isnull()]

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   property_name    2996 non-null   object 
 1   society          2996 non-null   object 
 2   price            2995 non-null   float64
 3   price_per_sqft   2995 non-null   float64
 4   areaWithType     2996 non-null   object 
 5   bedRoom          2996 non-null   int64  
 6   bathroom         2996 non-null   int64  
 7   balcony          2996 non-null   object 
 8   additionalRoom   2996 non-null   object 
 9   address          2990 non-null   object 
 10  floorNum         2996 non-null   object 
 11  facing           2123 non-null   object 
 12  agePossession    2995 non-null   object 
 13  nearbyLocations  2906 non-null   object 
 14  description      2996 non-null   object 
 15  furnishDetails   2199 non-null   object 
 16  features         2590 non-null   object 
 17  rating           26

In [67]:
df.head()

property_name                 society  price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency   0.45   
1        2 BHK Flat in Ashok Vihar            apna enclave   0.50   
2              2 BHK Flat in Sohna  tulsiani easy in homes   0.40   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard   1.47   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend   0.70   

   price_per_sqft                            areaWithType  bedRoom  bathroom  \
0          5000.0          Carpet area: 900 (83.61 sq.m.)        2         2   
1          7692.0          Carpet area: 650 (60.39 sq.m.)        2         2   
2          6722.0          Carpet area: 595 (55.28 sq.m.)        2         2   
3         12250.0        Carpet area: 1200 (111.48 sq.m.)        2         2   
4          5204.0  Super Built up area 1345(124.95 sq.m.)        2         2   

  balcony additionalRoom                              address floorNum facing  \
0       1  not available     Krishna Colony, Gurgaon, Haryana        4   West   
1       1  not available   46b, Ashok Vihar, Gurgaon, Haryana        1   West   
2       3  not available              Sohna, Gurgaon, Haryana       12    NaN   
3       2     study room  Sector 61 Gurgaon, Gurgaon, Haryana        2    NaN   
4       3     study room  Sector 92 Gurgaon, Gurgaon, Haryana        5    NaN   

        agePossession                                    nearbyLocations  \
0     1 to 5 Year Old  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1        10+ Year Old  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2     0 to 1 Year Old  ['Huda City Metro', 'Golf Course extn road', '...   
3            Dec 2023  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  Under Construction  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [68]:
# facing
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [69]:
df['facing'].isnull().sum()

np.int64(873)

In [70]:
df['facing'].fillna('NA',inplace=True)

/tmp/ipykernel_5776/3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)


In [71]:
df['facing'].value_counts()

facing
NA            873
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

Comment: From 'price' and 'price_per_sqft' column let's calculate the area 

In [72]:
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [73]:
df.head()

property_name                 society  price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency   0.45   
1        2 BHK Flat in Ashok Vihar            apna enclave   0.50   
2              2 BHK Flat in Sohna  tulsiani easy in homes   0.40   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard   1.47   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend   0.70   

   price_per_sqft    area                            areaWithType  bedRoom  \
0          5000.0   900.0          Carpet area: 900 (83.61 sq.m.)        2   
1          7692.0   650.0          Carpet area: 650 (60.39 sq.m.)        2   
2          6722.0   595.0          Carpet area: 595 (55.28 sq.m.)        2   
3         12250.0  1200.0        Carpet area: 1200 (111.48 sq.m.)        2   
4          5204.0  1345.0  Super Built up area 1345(124.95 sq.m.)        2   

   bathroom balcony additionalRoom                              address  \
0         2       1  not available     Krishna Colony, Gurgaon, Haryana   
1         2       1  not available   46b, Ashok Vihar, Gurgaon, Haryana   
2         2       3  not available              Sohna, Gurgaon, Haryana   
3         2       2     study room  Sector 61 Gurgaon, Gurgaon, Haryana   
4         2       3     study room  Sector 92 Gurgaon, Gurgaon, Haryana   

  floorNum facing       agePossession  \
0        4   West     1 to 5 Year Old   
1        1   West        10+ Year Old   
2       12     NA     0 to 1 Year Old   
3        2     NA            Dec 2023   
4        5     NA  Under Construction   

                                     nearbyLocations  \
0  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2  ['Huda City Metro', 'Golf Course extn road', '...   
3  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [74]:
df['area'].value_counts()

area
1650.0      53
1950.0      43
2000.0      33
1350.0      32
2400.0      24
2150.0      21
1900.0      20
1800.0      20
1300.0      20
1550.0      20
1578.0      19
1150.0      17
1450.0      17
2200.0      17
1400.0      17
600.0       16
1200.0      16
1500.0      16
1000.0      16
1930.0      15
1760.0      14
1640.0      14
1250.0      14
750.0       14
700.0       14
900.0       14
2350.0      14
1750.0      14
2010.0      13
1850.0      13
1600.0      13
2300.0      13
1975.0      13
2191.0      13
2100.0      13
650.0       12
3150.0      12
1423.0      12
1103.0      12
950.0       12
2812.0      12
2408.0      12
1245.0      11
1366.0      11
1997.0      11
2290.0      11
915.0       11
1100.0      11
1385.0      10
1929.0      10
2450.0      10
1050.0       9
1081.0       9
1700.0       9
1310.0       9
2660.0       9
2003.0       9
850.0        9
1360.0       9
990.0        8
3400.0       8
1380.0       8
2358.0       8
2600.0       8
1538.0       8
1620.0       8
1790.

In [75]:
# df.insert(loc=1,column='property_type',value='flat')

In [76]:
df.head()

property_name                 society  price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency   0.45   
1        2 BHK Flat in Ashok Vihar            apna enclave   0.50   
2              2 BHK Flat in Sohna  tulsiani easy in homes   0.40   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard   1.47   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend   0.70   

   price_per_sqft    area                            areaWithType  bedRoom  \
0          5000.0   900.0          Carpet area: 900 (83.61 sq.m.)        2   
1          7692.0   650.0          Carpet area: 650 (60.39 sq.m.)        2   
2          6722.0   595.0          Carpet area: 595 (55.28 sq.m.)        2   
3         12250.0  1200.0        Carpet area: 1200 (111.48 sq.m.)        2   
4          5204.0  1345.0  Super Built up area 1345(124.95 sq.m.)        2   

   bathroom balcony additionalRoom                              address  \
0         2       1  not available     Krishna Colony, Gurgaon, Haryana   
1         2       1  not available   46b, Ashok Vihar, Gurgaon, Haryana   
2         2       3  not available              Sohna, Gurgaon, Haryana   
3         2       2     study room  Sector 61 Gurgaon, Gurgaon, Haryana   
4         2       3     study room  Sector 92 Gurgaon, Gurgaon, Haryana   

  floorNum facing       agePossession  \
0        4   West     1 to 5 Year Old   
1        1   West        10+ Year Old   
2       12     NA     0 to 1 Year Old   
3        2     NA            Dec 2023   
4        5     NA  Under Construction   

                                     nearbyLocations  \
0  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2  ['Huda City Metro', 'Golf Course extn road', '...   
3  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   property_name    2996 non-null   object 
 1   society          2996 non-null   object 
 2   price            2995 non-null   float64
 3   price_per_sqft   2995 non-null   float64
 4   area             2995 non-null   float64
 5   areaWithType     2996 non-null   object 
 6   bedRoom          2996 non-null   int64  
 7   bathroom         2996 non-null   int64  
 8   balcony          2996 non-null   object 
 9   additionalRoom   2996 non-null   object 
 10  address          2990 non-null   object 
 11  floorNum         2996 non-null   object 
 12  facing           2996 non-null   object 
 13  agePossession    2995 non-null   object 
 14  nearbyLocations  2906 non-null   object 
 15  description      2996 non-null   object 
 16  furnishDetails   2199 non-null   object 
 17  features         25

In [78]:
df.shape

(2996, 19)

In [79]:
df.head()

property_name                 society  price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency   0.45   
1        2 BHK Flat in Ashok Vihar            apna enclave   0.50   
2              2 BHK Flat in Sohna  tulsiani easy in homes   0.40   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard   1.47   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend   0.70   

   price_per_sqft    area                            areaWithType  bedRoom  \
0          5000.0   900.0          Carpet area: 900 (83.61 sq.m.)        2   
1          7692.0   650.0          Carpet area: 650 (60.39 sq.m.)        2   
2          6722.0   595.0          Carpet area: 595 (55.28 sq.m.)        2   
3         12250.0  1200.0        Carpet area: 1200 (111.48 sq.m.)        2   
4          5204.0  1345.0  Super Built up area 1345(124.95 sq.m.)        2   

   bathroom balcony additionalRoom                              address  \
0         2       1  not available     Krishna Colony, Gurgaon, Haryana   
1         2       1  not available   46b, Ashok Vihar, Gurgaon, Haryana   
2         2       3  not available              Sohna, Gurgaon, Haryana   
3         2       2     study room  Sector 61 Gurgaon, Gurgaon, Haryana   
4         2       3     study room  Sector 92 Gurgaon, Gurgaon, Haryana   

  floorNum facing       agePossession  \
0        4   West     1 to 5 Year Old   
1        1   West        10+ Year Old   
2       12     NA     0 to 1 Year Old   
3        2     NA            Dec 2023   
4        5     NA  Under Construction   

                                     nearbyLocations  \
0  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2  ['Huda City Metro', 'Golf Course extn road', '...   
3  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [80]:
# extracting sector information from property_name column and adding a sector column
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [81]:
df['sector'] = df['sector'].str.lower()

In [82]:
df.head()

property_name                 society  price  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency   0.45   
1        2 BHK Flat in Ashok Vihar            apna enclave   0.50   
2              2 BHK Flat in Sohna  tulsiani easy in homes   0.40   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard   1.47   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend   0.70   

           sector  price_per_sqft    area  \
0  krishna colony          5000.0   900.0   
1     ashok vihar          7692.0   650.0   
2           sohna          6722.0   595.0   
3       sector 61         12250.0  1200.0   
4       sector 92          5204.0  1345.0   

                             areaWithType  bedRoom  bathroom balcony  \
0          Carpet area: 900 (83.61 sq.m.)        2         2       1   
1          Carpet area: 650 (60.39 sq.m.)        2         2       1   
2          Carpet area: 595 (55.28 sq.m.)        2         2       3   
3        Carpet area: 1200 (111.48 sq.m.)        2         2       2   
4  Super Built up area 1345(124.95 sq.m.)        2         2       3   

  additionalRoom                              address floorNum facing  \
0  not available     Krishna Colony, Gurgaon, Haryana        4   West   
1  not available   46b, Ashok Vihar, Gurgaon, Haryana        1   West   
2  not available              Sohna, Gurgaon, Haryana       12     NA   
3     study room  Sector 61 Gurgaon, Gurgaon, Haryana        2     NA   
4     study room  Sector 92 Gurgaon, Gurgaon, Haryana        5     NA   

        agePossession                                    nearbyLocations  \
0     1 to 5 Year Old  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1        10+ Year Old  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2     0 to 1 Year Old  ['Huda City Metro', 'Golf Course extn road', '...   
3            Dec 2023  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  Under Construction  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [83]:
df['sector'].value_counts()

sector
sohna                            159
sector 102                       113
sector 85                        110
sector 92                        100
sector 69                         92
sector 90                         90
sector 65                         89
sector 81                         87
sector 79                         80
sector 83                         68
sector 104                        65
sector 37d                        65
sector 86                         63
sector 107                        60
sector 95                         57
sector 108                        55
sector 89                         54
sector 70                         53
sector 37c                        53
sector 109                        52
sector 84                         51
sector-33 sohna                   49
sector 56                         44
sector 113                        43
sector 67                         42
sector 61                         41
sector 103                     

In [84]:
df['sector'].isnull().sum()

np.int64(0)

In [85]:
# replacing by actual sector
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [86]:
df['sector'].value_counts()

sector
sohna road                       159
sector 102                       113
sector 85                        110
sector 92                        100
sector 69                         92
sector 90                         90
sector 65                         89
sector 81                         87
sector 79                         80
sector 83                         68
sector 104                        67
sector 95                         66
sector 37d                        65
sector 86                         63
sector 89                         62
sector 107                        60
sector 33                         58
sector 108                        55
sector 37c                        53
sector 70                         53
sector 109                        52
sector 84                         51
sector 56                         44
sector 113                        43
sector 67                         42
sector 61                         41
sector 103                     

In [87]:
df[df['sector'] == 'new']

property_name                       society  price sector  \
2048  4 BHK Flat in New Gurgaon                        dlf 76   4.00    new   
2811  2 BHK Flat in New Gurgaon  takshila heights sector 37 c   0.67    new   
2907  2 BHK Flat in New Gurgaon                   green court   0.38    new   
2980  4 BHK Flat in New Gurgaon                    sare homes   0.85    new   

      price_per_sqft    area                            areaWithType  bedRoom  \
2048         11428.0  3500.0        Carpet area: 3500 (325.16 sq.m.)        4   
2811          5583.0  1200.0  Super Built up area 1200(111.48 sq.m.)        2   
2907          5507.0   690.0           Carpet area: 690 (64.1 sq.m.)        2   
2980          4786.0  1776.0     Super Built up area 1776(165 sq.m.)        4   

      bathroom balcony           additionalRoom  \
2048         4       2  study room,servant room   
2811         2       2            not available   
2907         2       1            not available   
2980         4       3            not available   

                            address floorNum facing       agePossession  \
2048  New Gurgaon, Gurgaon, Haryana        4     NA            Jun 2027   
2811  New Gurgaon, Gurgaon, Haryana        3     NA     1 to 5 Year Old   
2907  New Gurgaon, Gurgaon, Haryana        7     NA  Under Construction   
2980  New Gurgaon, Gurgaon, Haryana        3     NA    5 to 10 Year Old   

                                        nearbyLocations  \
2048  ['Shri Balaji Hospital and Trauma Center', 'S....   
2811  ['Shri Balaji Hospital and Trauma Center', 'S....   
2907  ['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...   
2980  ['Columbia Asia Hospital', 'Apex Multi Special...   

                                            description  \
2048  This lovely 4 bhk apartment/flat in new gurgao...   
2811  Check out this 2 bhk apartment for sale in tak...   
2907  We are the proud owners of this 2 bhk apartmen...   
2980  Located in the popular residential address of ...   

                                         furnishDetails  \
2048  ['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...   
2811                                                 []   
2907                                                 []   
2980                                                 []   

                                               features rating  
2048  ['Security / Fire Alarm', 'Feng Shui / Vaastu ...    NaN  
2811  ['Lift(s)', 'Swimming Pool', 'Visitor Parking'...    NaN  
2907  ['Intercom Facility', 'Lift(s)', 'Maintenance ...    NaN  
2980                                                NaN    NaN

In [88]:
df.loc[2811,'sector'] = 'sector 37'
df.loc[2980,'sector'] = 'sector 92'
df.loc[2907,'sector'] = 'sector 90'
df.loc[2048,'sector'] = 'sector 76'

In [89]:
df[df['sector'] == 'new sector 2']

property_name              society  price        sector  \
31    2 BHK Flat in New Palam Vihar  ompee k s residency   1.60  new sector 2   
89    2 BHK Flat in New Palam Vihar              my home   0.28  new sector 2   
2854  2 BHK Flat in New Palam Vihar              my home   0.22  new sector 2   

      price_per_sqft   area                    areaWithType  bedRoom  \
31           26936.0  594.0   Carpet area: 66 (55.18 sq.m.)        2   
89            3166.0  884.0  Carpet area: 900 (83.61 sq.m.)        2   
2854          4400.0  500.0  Carpet area: 500 (46.45 sq.m.)        2   

      bathroom balcony additionalRoom  \
31           2       2  not available   
89           1       1         others   
2854         2       1  not available   

                                         address floorNum facing  \
31             New Palam Vihar, Gurgaon, Haryana        1     NA   
89    F 150/b, New Palam Vihar, Gurgaon, Haryana        2     NA   
2854           New Palam Vihar, Gurgaon, Haryana        1     NA   

        agePossession                                    nearbyLocations  \
31    1 to 5 Year Old  ['Palam Vihar Vyapar kendra', 'Palam triangle'...   
89    1 to 5 Year Old  ['Palam Vihar Vyapar kendra', 'Palam triangle'...   
2854  0 to 1 Year Old  ['Palam Vihar Vyapar kendra', 'Palam triangle'...   

                                            description  \
31    We are the proud owners of this 2 bhk apartmen...   
89    2 bhk room with wooden coverd ,1 drawing room,...   
2854  Cctv surveillance are provided here. There is ...   

                                         furnishDetails  \
31                                                  NaN   
89    ['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...   
2854  ['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...   

                       features  \
31                          NaN   
89    ['Water Storage', 'Park']   
2854                        NaN   

                                                 rating  
31    ['Environment4 out of 5', 'Safety4 out of 5', ...  
89    ['Environment4 out of 5', 'Safety4 out of 5', ...  
2854  ['Safety4 out of 5', 'Lifestyle4 out of 5', 'E...

In [90]:
df.loc[[89,31,2854],'sector'] = 'sector 110'

In [91]:
df['sector'].value_counts()

sector
sohna road                       159
sector 102                       113
sector 85                        110
sector 92                        101
sector 69                         92
sector 90                         91
sector 65                         89
sector 81                         87
sector 79                         80
sector 83                         68
sector 104                        67
sector 95                         66
sector 37d                        65
sector 86                         63
sector 89                         62
sector 107                        60
sector 33                         58
sector 108                        55
sector 70                         53
sector 37c                        53
sector 109                        52
sector 84                         51
sector 56                         44
sector 113                        43
sector 67                         42
sector 61                         41
sector 103                     

In [92]:
df.duplicated().sum()

np.int64(0)

In [93]:
df.head()

property_name                 society  price      sector  \
0     2 BHK Flat in Krishna Colony  maa bhagwati residency   0.45    sector 7   
1        2 BHK Flat in Ashok Vihar            apna enclave   0.50    sector 3   
2              2 BHK Flat in Sohna  tulsiani easy in homes   0.40  sohna road   
3  2 BHK Flat in Sector 61 Gurgaon     smart world orchard   1.47   sector 61   
4  2 BHK Flat in Sector 92 Gurgaon        parkwood westend   0.70   sector 92   

   price_per_sqft    area                            areaWithType  bedRoom  \
0          5000.0   900.0          Carpet area: 900 (83.61 sq.m.)        2   
1          7692.0   650.0          Carpet area: 650 (60.39 sq.m.)        2   
2          6722.0   595.0          Carpet area: 595 (55.28 sq.m.)        2   
3         12250.0  1200.0        Carpet area: 1200 (111.48 sq.m.)        2   
4          5204.0  1345.0  Super Built up area 1345(124.95 sq.m.)        2   

   bathroom balcony additionalRoom                              address  \
0         2       1  not available     Krishna Colony, Gurgaon, Haryana   
1         2       1  not available   46b, Ashok Vihar, Gurgaon, Haryana   
2         2       3  not available              Sohna, Gurgaon, Haryana   
3         2       2     study room  Sector 61 Gurgaon, Gurgaon, Haryana   
4         2       3     study room  Sector 92 Gurgaon, Gurgaon, Haryana   

  floorNum facing       agePossession  \
0        4   West     1 to 5 Year Old   
1        1   West        10+ Year Old   
2       12     NA     0 to 1 Year Old   
3        2     NA            Dec 2023   
4        5     NA  Under Construction   

                                     nearbyLocations  \
0  ['Chintapurni Mandir', 'State bank ATM', 'Pear...   
1  ['Chintapurni Mandir', 'Sheetla Mata Mandir', ...   
2  ['Huda City Metro', 'Golf Course extn road', '...   
3  ['Sector 55-56 Metro station', 'Bestech Centra...   
4  ['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...   

                                         description  \
0  So with lift.Maa bhagwati residency is one of ...   
1  Property situated on main road, railway statio...   
2  This property is 15 km away from badshapur, gu...   
3  Near to metro station of sector 56 and opposit...   
4  We are the proud owners of this 2 bhk alongwit...   

                                      furnishDetails  \
0  ['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...   
1  ['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...   
2                                                NaN   
3                                                NaN   
4                                                 []   

                                            features  \
0  ['Feng Shui / Vaastu Compliant', 'Security / F...   
1  ['Security / Fire Alarm', 'Maintenance Staff',...   
2  ['Power Back-up', 'Feng Shui / Vaastu Complian...   
3  ['Security / Fire Alarm', 'Private Garden / Te...   
4                                                NaN   

                                              rating  
0  ['Environment4 out of 5', 'Safety4 out of 5', ...  
1  ['Environment4 out of 5', 'Safety4 out of 5', ...  
2  ['Environment4 out of 5', 'Safety4 out of 5', ...  
3                                                NaN  
4  ['Environment5 out of 5', 'Safety3 out of 5', ...

In [94]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [95]:
df.duplicated().sum()

np.int64(124)

In [96]:
df.shape

(2996, 16)

In [97]:
df.drop_duplicates(keep='first', inplace=True)

In [98]:
df.shape


(2872, 16)

In [99]:
df.to_csv('../data/flats_cleaned.csv',index=False)